[General]
Steps = 1
Camera = "Camera"
Visibility_Check = "Camera.001"
Scene = "Scene"
ShuffleWorld = true
CreateYoloLabels = true
CreateSegmentationMask = true
AnimateAlongPath = false
# creates images for every single object and stores them in seperate folders 
SingleObjects = false

[Files]
Folder = ""

[Config]
MultiConfig = false
Folder = "configs"


[Objects]
Names= ["Palette", "FrontHoles", "SideHoles", "Fork"]
Ignore= "" #["Camera","Light", "laubbaum", "nadelbaum", 'Camera.001', "ForkBase", "Fork1", "Fork2", "Palette2", "Palette3"]
Lamps = ""
Camera = "Camera"
Special= ""#["ForkBase"]         #["shelve4","shelve3","shelve2","shelve1"]
Decoy= ["laubbaum", "nadelbaum"] 

[SideHoles]
id  = 2
visibility_thresh_factor =0.0
hide_in_rgb = true

[FrontHoles]
id = 4
visibility_thresh_factor =0.0
hide_in_rgb = true

[Palette]
id = 3
visibility_thresh_factor =0.0

[Palette.Position]
X = [-0.45, 0.45]
X_normed_to_1m = true
X_hide_on_intersection = false

Y = [-0.20, 0.10]
Y_normed_to_1m = true
Y_hide_on_intersection = false

Z = [-1.5, -0.5]
Z_hide_on_intersection = false

[Palette.Rotation]
X = [-5, 5]
Y = [-180, 180]
Z = [-5, 5]

[Palette.Color]
NodeName="Mix"
PropertyName="Color2"
value1 = [0.0, 1.0]
value2 = [0.0, 0.1]
value3 = [0.8, 1.0]
mode = "hsv"

[Palette.PrincipledBSDF]
Metallic=[0.0, 0.3]
Specular=[0.1, 0.9]
SpecularTint=[0.0, 0.9]
Roughness=[0.1, 0.9]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.9]
SheenTint=[0.0, 0.8]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[Fork]
id = 1
visibility_thresh_factor =0.0

[Fork.Position]
X = [-0.04, 0.04]
X_normed_to_1m = false
X_hide_on_intersection = false

Y = [-0.14, -0.11]
Y_normed_to_1m = false
Y_hide_on_intersection = false

Z = [-0.3, -0.2]
Z_hide_on_intersection = false

[Fork.Rotation]
X = [-10, 0]
Y = [-8, 2]
Z = [-2, 2]

[Fork.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 1.0]
value2 = [0.0, 0.1]
value3 = [0.8, 1.0]
mode = "hsv"

[Fork.PrincipledBSDF]
Metallic=[0.0, 0.3]
Specular=[0.1, 0.9]
SpecularTint=[0.0, 0.9]
Roughness=[0.1, 0.9]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.9]
SheenTint=[0.0, 0.8]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[laubbaum]

[laubbaum.Position]
X = [-0.9, 0.9]
X_normed_to_1m = true
X_hide_on_intersection = true

Y = [-1.0, 0.2]
Y_normed_to_1m = true
Y_hide_on_intersection = true

Z = [-2.8, -0.0]
Z_hide_on_intersection = true

[laubbaum.Rotation]
X = [-45, 45]
Y = [-180, 180]
Z = [-25, 25]

[laubbaum.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 1.0]
value2 = [0.0, 0.5]
value3 = [0.2, 1.0]
mode = "hsv"

[laubbaum.PrincipledBSDF]
Metallic=[0.0, 0.8]
Specular=[0.1, 0.9]
SpecularTint=[0.0, 0.9]
Roughness=[0.1, 0.9]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.9]
SheenTint=[0.0, 0.8]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]


[nadelbaum]

[nadelbaum.Position]
X = [-0.9, 0.9]
X_normed_to_1m = true
X_hide_on_intersection = true

Y = [-1.0, 0.2]
Y_normed_to_1m = true
Y_hide_on_intersection = true

Z = [-2.8, -0.0]
Z_hide_on_intersection = true

[nadelbaum.Rotation]
X = [-45, 45]
Y = [-180, 180]
Z = [-25, 25]

[nadelbaum.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 1.0]
value2 = [0.0, 0.5]
value3 = [0.2, 1.0]
mode = "hsv"

[nadelbaum.PrincipledBSDF]
Metallic=[0.0, 0.8]
Specular=[0.1, 0.9]
SpecularTint=[0.0, 0.9]
Roughness=[0.1, 0.9]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.9]
SheenTint=[0.0, 0.8]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]


[World]
Backgrounds = "/home/vision/Study/DataGenPalettes/hdris/"

[Mask]
Mask_World = true

[Labels]
Palette= 2 
#FrontHoles = 3
#SideHoles = 4
#Fork = 5 
