[General]
Steps =500
Camera = "Camera"
Visibility_Check = "Camera.001"
Scene = "Scene"
ShuffleWorld = true
CreateYoloLabels = true
CreateSegmentationMask = false
AnimateAlongPath = false
# creates images for every single object and stores them in seperate folders 
SingleObjects = false

[Objects]
Names= ""
Ignore= ["Camera","CameraLight", "laubbaum", "nadelbaum", 'Camera.001']
Lamps = ""
Camera = "Camera"
Special= ["workstation"]         #["shelve4","shelve3","shelve2","shelve1"]
Decoy= ["laubbaum", "nadelbaum"] 

[laubbaum]
[laubbaum.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 1.0]
value2 = [0.0, 1.0]
value3 = [0.0, 1.0]
mode = "hsv"

[laubbaum.PrincipledBSDF]
Metallic=[0.0, 0.6]
Specular=[0.1, 0.9]
SpecularTint=[0.1, 0.9]
Roughness=[0.1, 0.9]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.9]
SheenTint=[0.0, 0.8]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[nadelbaum]
[nadelbaum.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 1.0]
value2 = [0.0, 1.0]
value3 = [0.0, 1.0]
mode = "hsv"

[nadelbaum.PrincipledBSDF]
Metallic=[0.0, 0.6]
Specular=[0.1, 0.9]
SpecularTint=[0.1, 0.9]
Roughness=[0.1, 0.9]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.9]
SheenTint=[0.0, 0.8]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[workstation]

[workstation.Disappear]
value = 0.5

[workstation.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 1.0]
value2 = [0.0, 0.05]
value3 = [0.8, 1.0]
mode = "hsv"

[workstation.PrincipledBSDF]
Metallic=[0.0, 0.3]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.2, 0.9]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.8]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[small_black_alu]
id = 1
visibility_thresh_factor = 0.6

[small_black_alu.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.0, 0.2]
mode = "hsv"

[small_black_alu.PrincipledBSDF]
Metallic=[0.4, 0.9]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.3, 1.0]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[small_grey_alu]
id = 2
visibility_thresh_factor = 0.6

[small_grey_alu.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.8, 1.0]
mode = "hsv"

[small_grey_alu.PrincipledBSDF]
Metallic=[0.6, 0.9]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.3, 0.6]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[large_black_alu]
id = 3
visibility_thresh_factor = 0.45

[large_black_alu.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.0, 0.2]
mode = "hsv"
[large_black_alu.PrincipledBSDF]
Metallic=[0.4, 1.0]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.5, 1.0]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[large_grey_alu]
id = 4
visibility_thresh_factor = 0.45

[large_grey_alu.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.8, 1.0]
mode = "hsv"
[large_grey_alu.PrincipledBSDF]
Metallic=[0.6, 0.9]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.3, 0.8]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[bolt]
id = 5
visibility_thresh_factor = 0.4

[bolt.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.0, 0.2]
mode = "hsv"
[bolt.PrincipledBSDF]
Metallic=[0.6, 1.0]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.1, 0.8]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[small_nut]
id = 6
visibility_thresh_factor = 0.35

[small_nut.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.1, 0.3]
mode = "hsv"
[small_nut.PrincipledBSDF]
Metallic=[0.3, 0.6]
Specular=[0.0, 0.2]
SpecularTint=[0.0, 0.2]
Roughness=[0.1, 0.8]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[large_nut]
id = 7
visibility_thresh_factor = 0.35

[large_nut.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.1, 0.3]
mode = "hsv"
[large_nut.PrincipledBSDF]
Metallic=[0.3, 0.6]
Specular=[0.0, 0.2]
SpecularTint=[0.0, 0.2]
Roughness=[0.1, 0.8]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[plastic_tube]
id = 8
visibility_thresh_factor = 0.75

[plastic_tube.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.0, 0.2]
mode = "hsv"
[plastic_tube.PrincipledBSDF]
Metallic=[0.0, 0.3]
Specular=[0.0, 0.2]
SpecularTint=[0.1, 0.4]
Roughness=[0.4, 0.9]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.2, 0.5]
Clearcoat=[0.05, 0.2]
ClearcoatRoughness=[0.0, 0.8]

[bearing_box]
id = 9
visibility_thresh_factor = 0.4

[bearing_box.Color]
NodeName="Mix"
PropertyName="Color2"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.7, 1.0]
mode = "hsv"
[bearing_box.PrincipledBSDF]
Metallic=[0.6, 0.9]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.1, 0.4]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[bearing_box.BrickTexture.Scale]
NodeName="Brick Texture"
PropertyName="Scale"
value = [50.0, 200.0]

[bearing_box.BrickTexture.Size]
NodeName="Brick Texture"
PropertyName="Mortar Size"
value = [0.0, 1.0]

[bearing_box.Brick.Smooth]
NodeName="Brick Texture"
PropertyName="Mortar Smooth"
value = [0.0,5.0]

[bearing_box.BrickTexture.Height]
NodeName="Brick Texture"
PropertyName="Row Height"
value = [0.1, 1.0]


[bearing_box.Mapping.Rotation]
0 = [0, 360]
1 = [0, 360]
2 = [0, 360]

[bearing_box.Mapping.Location]
1 = [0.0, 100.0]

[bearing]
id = 10
visibility_thresh_factor = 0.45

[bearing.Color]
NodeName="Mix"
PropertyName="Color2"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.7, 1.0]
mode = "hsv"
[bearing.PrincipledBSDF]
Metallic=[0.5, 0.8]
Specular=[0.1, 0.5]
SpecularTint=[0.0, 0.6]
Roughness=[0.3, 0.7]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[axis]
id = 11
visibility_thresh_factor = 0.4

[axis.Color]
NodeName="Mix"
PropertyName="Color2"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.7, 1.0]
mode = "hsv"
[axis.PrincipledBSDF]
Metallic=[0.7, 0.9]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.2, 0.4]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[distance_tube]
id = 12
visibility_thresh_factor = 0.5

[distance_tube.Color]
NodeName="Mix"
PropertyName="Color2"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.7, 1.0]
mode = "hsv"
[distance_tube.PrincipledBSDF]
Metallic=[0.5, 0.8]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.2, 0.4]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[motor]
id = 13
visibility_thresh_factor = 0.4

[motor.Color]
NodeName="Mix"
PropertyName="Color2"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.0, 0.1]
mode = "hsv"
[motor.PrincipledBSDF]
Metallic=[0.0, 0.9]
Specular=[0.1, 0.4]
SpecularTint=[0.1, 0.4]
Roughness=[0.7, 1.0]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.2, 0.5]
Clearcoat=[0.05, 0.2]
ClearcoatRoughness=[0.0, 0.8]

[blue_container]
id = 14
visibility_thresh_factor = 0.65

[blue_container.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.55, 0.7]
value2 = [0.4, 0.9]
value3 = [0.4, 0.9]
mode = "hsv"
[blue_container.PrincipledBSDF]
Metallic=[0.0, 0.3]
Specular=[0.2, 0.7]
SpecularTint=[0.1, 0.4]
Roughness=[0.1, 0.5]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.5]
SheenTint=[0.3, 0.8]
Clearcoat=[0.05, 0.2]
ClearcoatRoughness=[0.0, 0.8]

[red_container]
id = 15
visibility_thresh_factor = 0.65

[red_container.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.95, 1.0]
value2 = [0.5, 0.9]
value3 = [0.4, 0.9]
mode = "hsv"
[red_container.PrincipledBSDF]
Metallic=[0.0, 0.3]
Specular=[0.2, 0.7]
SpecularTint=[0.1, 0.4]
Roughness=[0.1, 0.5]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.5]
SheenTint=[0.3, 0.8]
Clearcoat=[0.05, 0.2]
ClearcoatRoughness=[0.0, 0.8]

[World]
Backgrounds = "/home/vision/atWork/DataGen/DataGenAtWork/hdris/"

[Path]
PathObject = "Robot"

[Mask]
Mask_World = true

# White
Mask_False_Objects = "Barriertape"
Mask_False_Mat = "Mask_False"
Mask_False_Color = [1,1,1,1]

# Black
Mask_True_Objects=""
Mask_True_Mat = "Mask_True"
Mask_True_Color = [0,0,0,1]

[Labels]
small_black_alu= 0 
small_grey_alu= 1 
large_black_alu= 2 
large_grey_alu= 3
bolt= 4 
small_nut= 5 
large_nut= 6 
plastic_tube= 7 
bearing_box= 8 
bearing= 9 
axis= 10 
distance_tube= 11 
motor= 12
blue_container= 13 
red_container= 14
