[General]
Steps = 500
Camera = "Camera"
Visibility_Check = "Camera.001"
Scene = "Scene"
ShuffleWorld = true
CreateYoloLabels = true
CreateSegmentationMask = true
AnimateAlongPath = false
# creates images for every single object and stores them in seperate folders 
SingleObjects = false
CheckVisibility = false

[Files]
Folder = "6DOF_realistic"

[Config]
MultiConfig = false
Folder = ""


[Objects]
Names= ""
Ignore= ["Camera","CameraLight", "laubbaum", "nadelbaum", 'Camera.001']
Lamps = ""
Camera = "Camera"
Special= ""#["workstation"]         #["shelve4","shelve3","shelve2","shelve1"]
Decoy= ["workstation"]  #"laubbaum", "nadelbaum", "workstation"] 

[laubbaum]
[laubbaum.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 1.0]
value2 = [0.0, 1.0]
value3 = [0.0, 1.0]
mode = "hsv"
material_name = ""

[laubbaum.PrincipledBSDF]
Metallic=[0.0, 0.6]
Specular=[0.1, 0.9]
SpecularTint=[0.1, 0.9]
Roughness=[0.1, 0.9]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.9]
SheenTint=[0.0, 0.8]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[nadelbaum]
[nadelbaum.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 1.0]
value2 = [0.0, 1.0]
value3 = [0.0, 1.0]
mode = "hsv"
material_name = ""

[nadelbaum.PrincipledBSDF]
Metallic=[0.0, 0.6]
Specular=[0.1, 0.9]
SpecularTint=[0.1, 0.9]
Roughness=[0.1, 0.9]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.9]
SheenTint=[0.0, 0.8]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[workstation]
id = 0
ShuffleMaterials = true

[workstation.Disappear]
value = 0.1

[workstation.Position]
X = [-0.3, 0.3]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.2, 0.2]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.45, -0.4]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[workstation.Rotation]
X = [-5, 5]
Y = [-5, 5]
Z = [-180, 180]


[workstation.Color1]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 1.0]
value2 = [0.0, 0.05]
value3 = [0.8, 1.0]
mode = "hsv"
material_name = "workstation"

[workstation.Color2]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 1.0]
value2 = [0.0, 0.05]
value3 = [0.8, 1.0]
mode = "hsv"
material_name = "clear_table"

[workstation.PrincipledBSDF]
Metallic=[0.0, 0.3]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.3, 0.9]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.8]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[small_black_alu]
id = 1
visibility_thresh_factor = 0.4

[small_black_alu.Position]
X = [-0.65, 0.65]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.35, 0.35]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[small_black_alu.Rotation]
X = [-180, 180]
Y = [-5, 5]
Z = [-180, 180]

[small_black_alu.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.0, 0.2]
mode = "hsv"
material_name = ""

[small_black_alu.PrincipledBSDF]
Metallic=[0.4, 0.9]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.3, 1.0]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[small_grey_alu]
id = 2
visibility_thresh_factor = 0.4

[small_grey_alu.Position]
X = [-0.65, 0.65]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.35, 0.35]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[small_grey_alu.Rotation]
X = [-180, 180]
Y = [-5, 5]
Z = [-180, 180]

[small_grey_alu.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.8, 1.0]
mode = "hsv"
material_name = ""

[small_grey_alu.PrincipledBSDF]
Metallic=[0.7, 0.9]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.1, 0.5]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[large_black_alu]
id = 3
visibility_thresh_factor = 0.2

[large_black_alu.Position]
X = [-0.6, 0.6]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.3, 0.3]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[large_black_alu.Rotation]
X = [-180, 180]
Y = [-5, 5]
Z = [-180, 180]

[large_black_alu.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.0, 0.2]
mode = "hsv"
material_name = ""

[large_black_alu.PrincipledBSDF]
Metallic=[0.4, 1.0]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.5, 1.0]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[large_grey_alu]
id = 4
visibility_thresh_factor = 0.2

[large_grey_alu.Position]
X = [-0.6, 0.6]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.3, 0.3]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[large_grey_alu.Rotation]
X = [-180, 180]
Y = [-5, 5]
Z = [-180, 180]

[large_grey_alu.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.8, 1.0]
mode = "hsv"
material_name = ""

[large_grey_alu.PrincipledBSDF]
Metallic=[0.7, 0.9]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.1, 0.5]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[bolt]
id = 5
visibility_thresh_factor = 0.2

[bolt.Position]
X = [-0.65, 0.65]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.35, 0.35]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[bolt.Rotation]
X = [-180, 180]
Y = [-5, 5]
Z = [-180, 180]

[bolt.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.0, 0.2]
mode = "hsv"
material_name = ""

[bolt.PrincipledBSDF]
Metallic=[0.6, 1.0]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.1, 0.8]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[small_nut]
id = 6
visibility_thresh_factor = 0.4

[small_nut.Position]
X = [-0.65, 0.65]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.35, 0.35]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[small_nut.Rotation]
X = [-10, 10]
Y = [-5, 5]
Z = [-180, 180]

[small_nut.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.1, 0.3]
mode = "hsv"
material_name = ""

[small_nut.PrincipledBSDF]
Metallic=[0.3, 0.6]
Specular=[0.0, 0.2]
SpecularTint=[0.0, 0.2]
Roughness=[0.1, 0.8]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[large_nut]
id = 7
visibility_thresh_factor = 0.4

[large_nut.Position]
X = [-0.65, 0.65]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.35, 0.35]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[large_nut.Rotation]
X = [-10, 10]
Y = [-5, 5]
Z = [-180, 180]

[large_nut.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.1, 0.3]
mode = "hsv"
material_name = ""

[large_nut.PrincipledBSDF]
Metallic=[0.3, 0.6]
Specular=[0.0, 0.2]
SpecularTint=[0.0, 0.2]
Roughness=[0.1, 0.8]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[plastic_tube]
id = 8
visibility_thresh_factor = 0.5

[plastic_tube.Position]
X = [-0.65, 0.65]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.35, 0.35]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[plastic_tube.Rotation]
X = [-10, 10]
Y = [-5, 5]
Z = [-180, 180]

[plastic_tube.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.0, 0.2]
mode = "hsv"
material_name = ""

[plastic_tube.PrincipledBSDF]
Metallic=[0.0, 0.3]
Specular=[0.0, 0.2]
SpecularTint=[0.1, 0.4]
Roughness=[0.4, 0.9]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.2, 0.5]
Clearcoat=[0.05, 0.2]
ClearcoatRoughness=[0.0, 0.8]

[bearing_box]
id = 9
visibility_thresh_factor = 0.4

[bearing_box.Position]
X = [-0.65, 0.65]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.35, 0.35]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[bearing_box.Rotation]
X = [-10, 10]
Y = [-5, 5]
Z = [-180, 180]

[bearing_box.Color]
NodeName="Mix"
PropertyName="Color2"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.7, 1.0]
mode = "hsv"
material_name = ""

[bearing_box.PrincipledBSDF]
Metallic=[0.7, 0.9]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.1, 0.3]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[bearing_box.BrickTexture.Scale]
NodeName="Brick Texture"
PropertyName="Scale"
value = [50.0, 200.0]

[bearing_box.BrickTexture.Size]
NodeName="Brick Texture"
PropertyName="Mortar Size"
value = [0.0, 1.0]

[bearing_box.Brick.Smooth]
NodeName="Brick Texture"
PropertyName="Mortar Smooth"
value = [0.0,5.0]

[bearing_box.BrickTexture.Height]
NodeName="Brick Texture"
PropertyName="Row Height"
value = [0.1, 1.0]


[bearing_box.Mapping.Rotation]
0 = [0, 360]
1 = [0, 360]
2 = [0, 360]

[bearing_box.Mapping.Location]
1 = [0.0, 100.0]

[bearing]
id = 10
visibility_thresh_factor = 0.55

[bearing.Position]
X = [-0.65, 0.65]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.35, 0.35]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[bearing.Rotation]
X = [-10, 10]
Y = [-5, 5]
Z = [-180, 180]

[bearing.Color]
NodeName="Mix"
PropertyName="Color2"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.7, 1.0]
mode = "hsv"
material_name = ""

[bearing.PrincipledBSDF]
Metallic=[0.7, 0.9]
Specular=[0.1, 0.5]
SpecularTint=[0.0, 0.6]
Roughness=[0.2, 0.5]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[axis]
id = 11
visibility_thresh_factor = 0.3

[axis.Position]
X = [-0.65, 0.65]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.35, 0.35]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[axis.Rotation]
X = [-10, 10]
Y = [-5, 5]
Z = [-180, 180]

[axis.Color]
NodeName="Mix"
PropertyName="Color2"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.7, 1.0]
mode = "hsv"
material_name = ""

[axis.PrincipledBSDF]
Metallic=[0.7, 0.9]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.1, 0.4]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[distance_tube]
id = 12
visibility_thresh_factor = 0.6

[distance_tube.Position]
X = [-0.65, 0.65]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.35, 0.35]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[distance_tube.Rotation]
X = [-10, 10]
Y = [-5, 5]
Z = [-180, 180]

[distance_tube.Color]
NodeName="Mix"
PropertyName="Color2"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.7, 1.0]
mode = "hsv"
material_name = ""

[distance_tube.PrincipledBSDF]
Metallic=[0.6, 0.9]
Specular=[0.2, 0.6]
SpecularTint=[0.0, 0.6]
Roughness=[0.2, 0.4]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.0, 0.2]
Clearcoat=[0.0, 0.8]
ClearcoatRoughness=[0.0, 0.8]

[motor]
id = 13
visibility_thresh_factor = 0.4

[motor.Position]
X = [-0.65, 0.65]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.35, 0.35]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[motor.Rotation]
X = [-10, 10]
Y = [-5, 5]
Z = [-180, 180]

[motor.Color]
NodeName="Mix"
PropertyName="Color2"
value1 = [0.0, 0.0]
value2 = [0.0, 0.0]
value3 = [0.0, 0.1]
mode = "hsv"
material_name = ""

[motor.PrincipledBSDF]
Metallic=[0.0, 0.9]
Specular=[0.1, 0.4]
SpecularTint=[0.1, 0.4]
Roughness=[0.7, 1.0]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.2]
SheenTint=[0.2, 0.5]
Clearcoat=[0.05, 0.2]
ClearcoatRoughness=[0.0, 0.8]

[blue_container]
id = 14
visibility_thresh_factor = 0.3

[blue_container.Position]
X = [-0.6, 0.6]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.3, 0.3]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[blue_container.Rotation]
X = [-5, 5]
Y = [-5, 5]
Z = [-180, 180]

[blue_container.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.55, 0.7]
value2 = [0.4, 0.9]
value3 = [0.4, 0.9]
mode = "hsv"
material_name = ""

[blue_container.PrincipledBSDF]
Metallic=[0.0, 0.3]
Specular=[0.2, 0.7]
SpecularTint=[0.1, 0.4]
Roughness=[0.1, 0.5]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.5]
SheenTint=[0.3, 0.8]
Clearcoat=[0.05, 0.2]
ClearcoatRoughness=[0.0, 0.8]

[red_container]
id = 15
visibility_thresh_factor = 0.3

[red_container.Position]
X = [-0.6, 0.6]
X_normed_to_1m = 'Z'
X_hide_on_intersection = true

Y = [-0.3, 0.3]
Y_normed_to_1m = 'Z'
Y_hide_on_intersection = true

Z = [-0.31, -0.29]
Z_normed_to_1m = ''
Z_hide_on_intersection = true

[red_container.Rotation]
X = [-5, 5]
Y = [-5, 5]
Z = [-180, 180]

[red_container.Color]
NodeName="Principled BSDF"
PropertyName="Base Color"
value1 = [0.95, 1.0]
value2 = [0.5, 0.9]
value3 = [0.4, 0.9]
mode = "hsv"
material_name = ""

[red_container.PrincipledBSDF]
Metallic=[0.0, 0.3]
Specular=[0.2, 0.7]
SpecularTint=[0.1, 0.4]
Roughness=[0.1, 0.5]
Anisotropic=[0.0, 0.9]
AnisotropicRotation=[0.0, 0.9]
Sheen=[0.0, 0.5]
SheenTint=[0.3, 0.8]
Clearcoat=[0.05, 0.2]
ClearcoatRoughness=[0.0, 0.8]

[World]
Backgrounds = "/home/vision/Study/DataGenAtworkSegmentation/hdris/"

[Path]
PathObject = "Robot"

[Mask]
Mask_World = true

# White
Mask_False_Objects = "Barriertape"
Mask_False_Mat = "Mask_False"
Mask_False_Color = [1,1,1,1]

# Black
Mask_True_Objects=""
Mask_True_Mat = "Mask_True"
Mask_True_Color = [0,0,0,1]

[Labels]
small_black_alu= 1
small_grey_alu= 2
large_black_alu= 3 
large_grey_alu= 4
bolt= 5
small_nut= 6 
large_nut= 7 
plastic_tube= 8 
bearing_box= 9
bearing= 10
axis= 11
distance_tube= 12 
motor= 13
blue_container= 14 
red_container= 15


